# Generated by Django 4.1.5 on 2023-01-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
