# Generated by Django 4.0.4 on 2022-12-31 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount_charged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.IntegerField(null=True)),
                ('amount_owned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department', models.CharField(blank=True, choices=[('Human Resources', 'Hr'), ('IT', 'It'), ('Research and Development', 'Rnd'), ('Marketing', 'Marketing'), ('Production', 'Production')], max_length=50)),
                ('first_CFO_approved', models.BooleanField(default=False)),
                ('second_CFO_approved', models.BooleanField(default=False)),
                ('approved_date', models.DateField(null=True)),
                ('item', models.ManyToManyField(to='invoice.item')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.employeeprofile')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.vendorprofile')),
            ],
        ),
    ]
