# Generated by Django 4.0.4 on 2023-01-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceedit',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
